### DISCUSSION TITLE
Customization

### DISCUSSION THREAD

**Discussion by manuelkamp** [enchant97/hasty-paste#38] [Q&A] [answered]
Hi, how is it possible to customize a docker installation? I want to change favicon, page title and the big image on the start page? Also it would be nice to change page colors, if possible.

**Comment by enchant97** [comment, marked as answer]
You can't currently change the icon+title. As for changing the theme, you can't customise this at the moment.

I will add these to the task list, as they seem useful to have. Pull requests are welcome, if you are able to contribute code.

**Reply by enchant97** [reply]
@manuelkamp just thought I would update this answer, all features are now implemented in V1.5.

**Reply by manuelkamp** [reply]
@enchant97 thanks - I just tried it and the settings work, except the logo and favicon. This is the docker-compose.yml:
`version: "3"

services:
  paste-bin:
    container_name: paste-bin
    image: ghcr.io/enchant97/hasty-paste:1
    restart: unless-stopped
    volumes:
      - data:/app/data
    ports:
      - 8000:8000
    environment:
      - "UI_DEFAULT__USE_LONG_ID=False"
      - "NEW_AT_INDEX=True"
      - "UI_DEFAULT__EXPIRE_TIME__ENABLE=True"
      - "UI_DEFAULT__EXPIRE_TIME__DAYS=14"
      - "BRANDING__TITLE=Sometitle"
      - "BRANDING__DESCRIPTION=Somedesc"
      - "BRANDING__FAVICON=/opt/custom/favicon.ico"
      - "BRANDING__ICON=/opt/custom/logo.svg"
      - "MAX_BODY_SIZE=4000000"

volumes:
  data:`

and of course I uploaded the two files on my server where I run the docker container on into the specified path. I tried chmod 777 them, without success.

**Reply by enchant97** [reply]
If the compose file you have listed is the exactly the same, you are missing the volume mount for your icons:

```yaml
version: "3"

services:
  paste-bin:
  container_name: paste-bin
  image: ghcr.io/enchant97/hasty-paste:1
  restart: unless-stopped
  volumes:
    - data:/app/data
    # This is missing, (ro is for readonly, optional but good to have)
    - /opt/custom:/opt/custom:ro
  ports:
    - 8000:8000
  environment:
    - "UI_DEFAULT__USE_LONG_ID=False"
    - "NEW_AT_INDEX=True"
    - "UI_DEFAULT__EXPIRE_TIME__ENABLE=True"
    - "UI_DEFAULT__EXPIRE_TIME__DAYS=14"
    - "BRANDING__TITLE=Sometitle"
    - "BRANDING__DESCRIPTION=Somedesc"
    - "BRANDING__FAVICON=/opt/custom/favicon.ico"
    - "BRANDING__ICON=/opt/custom/logo.svg"
    - "MAX_BODY_SIZE=4000000"

volumes:
  data:
```
